# Generated by Django 3.1.1 on 2020-09-13 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('Nombre_restaurant', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=400)),
                ('Direccion', models.CharField(max_length=200)),
                ('Telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('approved_comment', models.BooleanField(default=False)),
                ('Id_Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='restaurantes.restaurant')),
            ],
        ),
    ]
