# Generated by Django 3.1 on 2020-09-18 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0005_auto_20200916_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioChimenea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('Nombre_restaurant', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('valoracion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioJose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('Nombre_restaurant', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('valoracion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioLomo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('Nombre_restaurant', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('valoracion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioNanas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('Nombre_restaurant', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('valoracion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioSurtidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('Nombre_restaurant', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('valoracion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
