# Generated by Django 3.1 on 2020-09-23 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0006_comentariochimenea_comentariojose_comentariolomo_comentarionanas_comentariosurtidor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
